# Generated by Django 2.2.8 on 2019-12-12 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('sold_out', 'Sold Out')], default='ready', max_length=10)),
                ('harga', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Minuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('sold_out', 'Sold Out')], default='ready', max_length=10)),
                ('harga', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField(default=0)),
                ('nomor_meja', models.IntegerField()),
                ('kode_pesanan', models.CharField(max_length=15, null=True)),
                ('lunas', models.BooleanField(default=False)),
                ('bayar', models.FloatField(default=0.0)),
                ('kembalian', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pelayan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesanan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DaftarPesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makanan_jumlah', models.IntegerField(default=1)),
                ('minuman_jumlah', models.IntegerField(default=1)),
                ('makanan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daftar_pesanan_makanan', to='pesanan.Makanan')),
                ('minuman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daftar_pesanan_minuman', to='pesanan.Minuman')),
                ('pesanan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daftar_pesanan', to='pesanan.Pesanan')),
            ],
        ),
    ]
